name: Build and Deploy Wisecow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ github.repository_owner }}
  IMAGE_NAME: wisecow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix wisecow.sh syntax
        run: sed -i 's/main)/main/' wisecow.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest,${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Update deployment image
        run: |
          sed -i "s|\${DOCKER_USERNAME}|${{ env.DOCKER_USERNAME }}|g" kubernetes/wisecow-deployment.yaml
          kubectl apply -f kubernetes/wisecow-deployment.yaml
          kubectl apply -f kubernetes/wisecow-service.yaml
          kubectl apply -f kubernetes/wisecow-ingress.yaml

      - name: Wait for deployment to be ready
        run: |
          kubectl rollout status deployment/wisecow